models/Project.php
<?php

namespace app\models;

use Yii;
use app\boffins_vendor\classes\FolderSubComponentARModel;
use app\boffins_vendor\behaviors\ComponentsBehavior;
use app\boffins_vendor\behaviors\DeleteUpdateBehavior;
use app\boffins_vendor\behaviors\DateBehavior;
/**
 * This is the model class for table "{{%project}}".
 *
 * @property string $tyc_ref
 * @property integer $project_id
 * @property integer $client_id
 * @property integer $supplier_id
 * @property string $client_reference
 * @property string $manufacturer_ref
 * @property string $project_status
 * @property string $pro_description
 *
 * @property Order[] $Orders
 * @property Client $client
 * @property Supplier $supplier
 */
class Project extends FolderSubComponentARModel
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%project}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['client_id', 'supplier_id','client_reference', 'manufacturer_ref','pro_description'], 'required'],
            [['client_id', 'supplier_id'], 'integer'],
            [['itemType', 'itemID'], 'safe'],
            [['client_reference', 'manufacturer_ref'], 'string', 'max' => 30],
            [['project_status'], 'string', 'max' => 255],
            [['client_id'], 'exist', 'skipOnError' => true, 'targetClass' => Client::className(), 'targetAttribute' => ['client_id' => 'id']],
            [['supplier_id'], 'exist', 'skipOnError' => true, 'targetClass' => Supplier::className(), 'targetAttribute' => ['supplier_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'tyc_ref' => 'Tyc Ref',
            'project_id' => 'Project',
            'client_id' => 'Client',
            'supplier_id' => 'Supplier',
            'client_reference' => 'Client Reference',
            'manufacturer_ref' => 'Manufacturer Ref',
            'project_status' => 'Project Status',
            'pro_description' => 'Description',
        ];
    }
	
	public function getDescriptions()
    {
        return $this->pro_description;
        
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOrders()
    {
        return $this->hasMany(Order::className(), ['tyc_ref' => 'tyc_ref']);
    }
	
	public function getFolderComponent()
    {
        return $this->hasOne(FolderComponent::className(), ['component_id' => 'component_id']);
    }
	
	public function getTycref(){
		return !empty($this->folderComponent->folder_id)? $this->folderComponent->listFolders : 'Not in a folder yet';
	}
	
	public function getFolderDescription(){
		return $this->hasOne(Folder::className(), ['tyc_ref' => 'tycref']);
	}
	
	

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getClient()
    {
        return $this->hasOne(Client::className(), ['id' => 'client_id']);
    }
    

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSupplier()
    {
        return $this->hasOne(Supplier::className(), ['id' => 'supplier_id']);
    }
    
    //fetch the total number of projects added by kingsley of buffins 
    public function allrecords()
	{
        return Count($this->find()->all());
    }
    
    public static function get_project_comments($project_id,$type)
	{
        $remark=Remark::get_project_comment($project_id,$type);
        return $remark;
    }
        
    public static function get_allproject_comments($id)
	{
        $remark=Remark::get_allproject_comment($id);
        return $remark;
    }
	
    public function display_projects()
	{
		$project= $this->find()
    		->asArray()
			->all();
        return $project;
    }
	
	public function getId(){
		return $this->project_id;
	}
		
	public function init() 
	{
		parent::init();
		// $this->on(Components::EVENT_AFTER_SOFT_DELETES, [$this, 'test']);
		 
	}
	
	
	
    
}

controllers/ProjectController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Project;
use app\models\Folder;
use app\models\ProjectSearch;
use app\models\Corporation;
use app\models\Remark;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\helpers\Html;
use app\models\Component as component;
use app\models\FolderComponent as folderComponent;
use app\models\StatusType ;
use app\models\Client ;
use app\models\Supplier ;
use app\boffins_vendor\classes\BoffinsBaseController;

/**
 * TmprojectController implements the CRUD actions for Tmproject model.
 */
class ProjectController extends BoffinsBaseController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::classname(),
                'only' => ['create','update'],
                'rules' => [
                    [
            'allow'=>true,
                 //   'rules'=>[@],
                        ],
                    
            
                ]
            ],
            
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Tmproject models.
     * @return mixed
     */
    public function actionIndex()
    {
        //$searchModel = new ProjectSearch();
        //$dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $model = new Project;
        $root_method = $model->display_projects();
		$findOneProject = $model->find()->orderBy(['project_id'=>SORT_ASC])->one();

        return $this->render('index', [
            //'searchModel' => $searchModel,
            //'dataProvider' => $dataProvider,
            'projects' => $root_method,
			'findOneProject' => $findOneProject,
			'model' => $model,
        ]);
    }
	
	public function actionProjectlistview()
    {
        $searchModel = new ProjectSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $model = new Project();
		$allProjects = Project::findAll([]);
        
		$status = new StatusType();

		if(isset($_POST['option'])){
			$option = $_POST['option'];
			$hoverEffect = 'false';
			$newOption = explode(',',$option);
			$root_method =$model->find()->where(['component_id'=>array_values($newOption)])->all();
		} else {
			$hoverEffect = 'true';
			$root_method = $model->find()->all();
		}
        return $this->renderAjax('projectlistview', [
            'searchModel' => $allProjects,
            'dataProvider' => $dataProvider,
            'projects' => $root_method,
			'status' => $status,
        ]);
    }

    /**
     * Displays a single Tmproject model.
     * @param integer $id
     * @return mixed
     */
    
    public function actionView($id)
    {   
		$model = $this->findModel($id);
	 	$component = new Project;
		$testcomponent = Project::findOne($id);
		$testcomponent2 = $testcomponent->subComponents;
       // $folder = Folder::selectone($model->tyc_ref);
        $projectcomment = Project::get_project_comments($id,$model->project_id,'project');
        $invoicecomment = Project::get_project_comments($id,$model->project_id,'invoice');
        $ordercomment = Project::get_project_comments($id,$model->project_id,'order');
        $allcomment = Project::get_allproject_comments($id,$model->project_id,'order');
        $remark = new Remark();
		
        return $this->render('view', [
            'model' => $model ,
            'folderdetails' => 'test',//$folder,
            'projectcomment' => $projectcomment,
            'invoicecomment' => $invoicecomment,
            'ordercomment' => $ordercomment,
            'remark' => $remark,
            'allremark' => $allcomment,
			'testcomponent2' => $testcomponent2,
			
            
        ]);
    }
	
	
	
	public function actionProjectview($id)
    {   if($id == 0 or $id === 0 ){
		return $this->renderAjax('/nodata/nodataavailable',['message'=>'No Project available']);
	}
		$model = $this->findModel($id);
	 	$component = new Project;
		$testcomponent = Project::findOne($id);
		$testcomponent2 = $testcomponent->subComponents;
        //$folder = Folder::selectone($model->tyc_ref);
        $projectcomment = Project::get_project_comments($id,'project');
        $invoicecomment = Project::get_project_comments($id,'invoice');
        $ordercomment = Project::get_project_comments($id,'order');
        $allcomment = Project::get_allproject_comments($id,'order');
        $remark = new Remark();
	 
		if(isset($_POST['var2']) and $_POST['var2'] == 1){
			return $this->renderAjax('projectview', [
				'model' => $model ,
				'folderdetails' => 'test',//$folder,
				'projectcomment' => $projectcomment,
				'invoicecomment' => $invoicecomment,
				'ordercomment' => $ordercomment,
				'remark' => $remark,
				'allremark' => $allcomment,
				'testcomponent2' => $testcomponent2,
				'subComponents' => $model->subComponents


			]);
		}else {
			return $this->renderAjax('projectview', [
            'model' => $model ,
            'folderdetails' => 'test',//$folder,
            'projectcomment' => $projectcomment,
            'invoicecomment' => $invoicecomment,
            'ordercomment' => $ordercomment,
            'remark' => $remark,
            'allremark' => $allcomment,
			'testcomponent2' => $testcomponent2,
			'subComponents' => $model->subComponents
			
            
        ]);
		}
    }


    /**
     * Creates a new Tmproject model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {	//instantiating  of all required model
		$model = new Project();
		
		$folderModel = Folder::find()->all();
        $clientModel=Client::find()->all();
        $supplierModel=Supplier::find()->all(); 
		
		if(isset($_GET['id'])){
			$getId = $_GET['id'];
			if(!empty($model->itemType) && !empty($model->itemID)){
				$model->itemType = $model->itemType.',folder';
				$this->owner->itemID = $model->itemID.','.$getId;
			} else{
				$model->itemType = 'folder';
				$model->itemID = $getId;
			}
		}
		
			if ($model->load(Yii::$app->request->post()) && $model->save()) {
				
				$data=[];
				Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
				$data['sent'] = 'sent';
				$data['message'] = 'New project was created with project id '.$model->project_id;
				
				return $data;
			}
		
                
            return $this->renderAjax('create', [
                'client' => $clientModel,
                'supplier' => $supplierModel,
                'model' => $model,
                'folder' => $folderModel,
				
				
            ]);
        
    }

    /**
     * Updates an existing Tmproject model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
		
		$folderComponent = new folderComponent();
		$component = new component();
		//calling of required  model methods
		$folderModel = Folder::find()->all();
        $clientModel=Client::find()->all();
        $supplierModel=Supplier::find()->all();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
			$data=[];
			Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
			$data['sent'] = 'sent';
			$data['message'] = 'Updated project  with project id '.$model->project_id;
			return $data;
        } else {
            return $this->renderAjax('update', [
               'client' => $clientModel,
                'supplier' => $supplierModel,
                'model' => $model,
                'folder' => $folderModel,
				'folderComponent' => $folderComponent
            ]);
        }
    }

    /**
     * Deletes an existing Tmproject model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
        return $this->redirect(['index']);
    }

    /**
     * Finds the Tmproject model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Tmproject the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Project::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
    
    static function convert_tycref_tag($str)
	{
        $regex = "/tyc_ref+([a-zA-Z0-9_]+)/";
        $str = preg_replace_callback($regex, 'self::convertTycrefLink', $str);
        return($str);
    }
    
    public static function convertTycrefLink($value1)
	{
        $values = Html::a($value1[0], ['folder/view','id' => $value1[1]]);
        return $values;
    }
    
    
    public function actionCreateremark($id)
    {
        $remark = new Remark();
        $model = $this->findModel($id);
        $folder = folderComponent::find()->where(['component_id'=>$model->component_id])->one()->tyc_ref;
        $remark->tyc_ref = $folder;
   
        if ($remark->load(Yii::$app->request->post()) && $remark->save()) {
            $creat_folder_project = Yii::$app->session;
            
            //return $this->redirect(['view', 'id' =>$id]);
			$data=[];
			Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
			$data['sent'] = 'sent';
			$data['message'] = 'Created a new Remark';
			return $data;
        } else { 
        echo 0;
        }
    }
}

views/project/_form.php
<?php


use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use app\boffins_vendor\components\controllers\ComponentLinkWidget;
use app\models\FolderComponent;
use app\models\StatusType as status;
use yii\widgets\Pjax;


/* @var $this yii\web\View */
/* @var $model app\models\Tmproject */
/* @var $form yii\widgets\ActiveForm */

$clientUrl = Url::to(['client/adhockclient']);
$supplierUrl = Url::to(['supplier/adhocsupplier']);
?>


<style>
    .form_form_input{
        resize:none;
        width:100%;
    }
	
	#projectloader,#iprojectloader1 {
		display: none;
	}
	
	.glyphicon.active{
		color: red !important;
	}
</style>
<section>
	
<div class="project-form">

    <?php $form = ActiveForm::begin(['enableClientValidation' => true,'id'=>'projectforms', 'attributes' => $model->attributes(),'enableAjaxValidation' => false,]); ?>
	
	<?= ComponentLinkWidget::widget(['model'=>$model,'form'=>$form]); ?>
    

	<?php Pjax::begin(['id' => 'clientRefresh','timeout' => 5000]); ?>
	<?= $form->field($model, 'client_id',['options'=>[
                'tag'=>'div',
                'class'=>'form-group clientRefesh'],
                'template'=>'{label} <i class="glyphicon glyphicon-plus active newClients" title="Add new Client" data-Url="'.$clientUrl.'"></i>{input}{error}{hint}'
                    ])->dropdownList(ArrayHelper::map($client, 'id', 'name'));?>
	<?php Pjax::end(); ?>
	
	<?= $form->field($model, 'supplier_id',['options'=>[
                'tag'=>'div',
                'class'=>'form-group supplierRefesh'],
                'template'=>'{label} <i class="glyphicon glyphicon-plus active newSuppliers"  title="Add new Supplier" data-Url="'.$supplierUrl.'" ></i>{input}{error}{hint}'
                    ])->dropdownList(ArrayHelper::map($supplier, 'id', 'name'));?>


    <?= $form->field($model, 'client_reference')->textInput(['maxlength' => true]) ?>
	
    <?= $form->field($model, 'pro_description')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'manufacturer_ref')->textInput(['maxlength' => true]) ?>
    
	<?= $form->field($model, 'project_status')->dropDownList(ArrayHelper::map(status::find()->where(['status_group'=>'project'])->all(), 'id', 'status_title')) ?>
    
    
    
    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? '<span id="projectbuttonText">Create</span> <img id="projectloader" src="images/45.gif" " /> <span id="projectloader1"><span>' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-basic' : 'btn btn-basic','id'=>'projectsubmit_id']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>



</section>

views/project/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Tmprojectsearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="project-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'tyc_ref') ?>

    <?= $form->field($model, 'project_id') ?>

    <?= $form->field($model, 'client_id') ?>

    <?= $form->field($model, 'supplier_id') ?>

    <?= $form->field($model, 'client_reference') ?>

    <?php // echo $form->field($model, 'manufacturer_ref') ?>

    <?php // echo $form->field($model, 'project_status') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/project/index.php
 <style>
 
    .floatright {
        float: right;
    }
	
    .foldernote {
        line-height: 24px;
        text-underline-position: alphabetic;
        margin-top: 10px;
    }
	
	#proloader {
		display:none;
	}
	
	#flash {
		display: none;
	}
	 
</style>
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\DetailView;
use app\models\Corporation;
use yii\bootstrap\Alert;
use app\models\Supplier;
use app\boffins_vendor\components\controllers\Menu;
use yii\bootstrap\Modal;

/* @var $this yii\web\View */
/* @var $model app\models\Folder */
$this->title = 'Tycol | Project';
$this->params['breadcrumbs'][] = ['label' => ' Folders', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<?php $this->beginBlock('folderview'); ?>
Project
<small>Select Project</small>
   
<?php $this->endBlock(); ?>

<?php $this->beginBlock('folderSidebar'); ?>
	<?= Menu::widget(); ?>

<?php $this->endBlock(); ?>

<div class="folder-view">

    

    <!--<p>
        <?= Html::a('Update', ['update', 'id' => 1], ['class' => 'btn btn-danger']) ?>
        <?= Html::a('Delete', ['delete', 'id' => 1], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p> -->

   

</div>



<section class="content">
    <!-- flash messages start -->
    <? if (Yii::$app->session->getFlash('created_successfully') !==NULL): ?>
		 <?= Alert::widget([
	   'options' => ['class' => 'alert-info'],
	   'body' => Yii::$app->session->getFlash('created_successfully'),
		 ]);?>
    <? endif ?>
    
    <? if (Yii::$app->session->getFlash('created_folder') !==NULL): ?>
		 <?= Alert::widget([
	   'options' => ['class' => 'alert-info'],
	   'body' => Yii::$app->session->getFlash('created_folder'),
		 ]);?>
    <? endif ?>
    
    <? if (Yii::$app->session->getFlash('instruction') !==NULL): ?>
		 <?= Alert::widget([
	   'options' => ['class' => 'alert-info'],
	   'body' => Yii::$app->session->getFlash('instruction'),
		 ]);?>
    <? endif ?>
    <!-- flash messages end -->
	
	<div class="row">
		<div class="col-lg-12">
			<?= Alert::widget([
				   'options' => ['class' => 'alert-info','id'=>'flash'],
				   'body' => Yii::$app->session->getFlash('created_successfully'),
					 ]);?>
		</div>
	</div>
      <div class="row">
          
          
          
          
          
		  <div class="col-xs-7 " >
			  <? $projectId=''; if($model->find()->count() <= 0){$projectId=1; echo 'no records';}else{$projectId=!empty($findOneProject->project_id)?$findOneProject->project_id:0; } ?>
			  
			  <div id="projectListView">
			  <img class="loadergif" src="images/loader.gif"  />
			  </div>
			
		  </div>
		  
		  <div class="col-xs-5 " style="padding:0px !important;margin-top: 20px !important">
			  
			  <div id="projectviewcontainer" class="fixede">
				  <div id="projectView" style='position: relative;'>
				  <img class="loadergif" src="images/loader.gif"  />
				  </div>
				  
			  </div>

			  
	</div>
		  </div>
    </div>
</section>

<? 
		Modal::begin([
			'header' =>'<h1 id="headers"></h1>',
			'id' => 'dashboard',
			'size' => 'modal-md',  
		]);
?>
<div id="formcontent"></div>
<?
	Modal::end();
?>


<? 
		Modal::begin([
			'header' =>'<h1 id="headers"></h1>',
			'id' => 'clientsupplier',
			'size' => 'modal-sm',  
		]);
?>
<div id="contentclientnsuppliers"></div>
<?
	Modal::end();
?>





<?php 
	$urlListView = Url::to(['project/projectlistview']);
	$urlView = Url::to(['project/projectview','id'=>$projectId]);
	
$js3 = <<<JS
$("#projectListView").load('$urlListView');
$("#projectView").load('$urlView',{var2:1});
$(document).on('click','.projecturl',function(){
var parent = $(this).parent();

$('.projecturltr').removeClass('activelist');
parent.addClass('activelist');

$('#projectviewcontainer').fadeOut('fast');
$('#projectView').html('<img class="loadergif" src="images/loader.gif" " />');
var url = parent.data('url');
$("#projectView").load(url,{var2:1},function(){

$('#projectviewcontainer').slideDown('fast');

});
})



$(document).on('click','#createproject',function(){
var formUrl = $(this).data('formurl');




$.ajax({
  url: formUrl,
  headers: {
     'Cache-Control': 'no-cache, no-store, must-revalidate', 
     'Pragma': 'no-cache', 
     'Expires': '0'
   },
  
  success: function(response){
  console.log(response);
    $('#projectviewcreate').modal('show').find('#projectcreateform').html(response);
  },
  
});
})

$(document).on('click','#projectnewremark',function(){
$('#projectviewremark').modal('show').find('#projectremark');

})



JS;
 
$this->registerJs($js3);
?>



																  
																  
																  

views/project/projectlistview.php
<style>
    .floatright {
		float: right;
		margin:10px;
    }
	
    .foldernote {
        line-height: 24px;
        text-underline-position: alphabetic;
        margin-top: 10px;
    }
	.projecturl {
		cursor: pointer;
	}
   #box {
		border: none;
		margin-top: 0px;
    }
	
   .box-body h3 {
		font-family: calibri !important;
		margin-top: 0px !important;
		width:50% !important;
		text-align:left;
	}
   
</style>
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\DetailView;
use yii\bootstrap\Alert;
use yii\bootstrap\Modal;
use app\models\Corporation;
use app\models\Supplier;

/* @var $this yii\web\View */
/* @var $model app\models\Folder */
?>

<div class="folder-view">

    <h1><?= Html::encode($this->title) ?></h1>
    <!--<p>
        <?= Html::a('Update', ['update', 'id' => 1], ['class' => 'btn btn-danger']) ?>
        <?= Html::a('Delete', ['delete', 'id' => 1], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p> -->
</div>

<div class="row">
	<div class="col-xs-12">
		<div class="box"  style="border-radius:5px !important;border: none;">
			<div class="folder-index">
				<h1><?= Html::encode($this->title) ?> 
					<div class="floatright btn btn-danger" id="createproject" data-formurl="<?= Url::to(['create']) ?>">Create New Project
					</div>
				</h1>
	
				<div class="box-body" id = "project-title">
					<h3>Projects List</h3>
					<table id="projectlistview" class="table table-bordered table-striped">
						
						<thead>
							<tr>
								<th>SN</th>
								<th>Folder</th>
								<th>Description</th>
								<th>Client</th>
								<th>Supplier</th>
								<th>Status</th>
								<th>Action</th>
							</tr>
						</thead>
						
						<tbody>
							<?php $sn = 1; foreach ($projects as $k => $v) { ?>
							
							<tr class="projecturltr <?if($sn === 1){echo 'activelist';} ?>" data-url="<?=Url::to(['project/projectview','id' => $v['project_id']]) ?>" title="Click to view project">
							
								<td class="projecturl"><?= $sn; ?></td>
								<td class="projecturl"><?= !empty($v['tycref']) && is_array($v['tycref']) ? implode("</br>", $v['tycref']) : 'not Available';  ?></td>
								<td class="projecturl"><?= $v['pro_description'];  ?></td>
								<td class="projecturl"><?= Corporation::getclientname($v['client_id']);  ?></td>
								<td class="projecturl"><? $supplier = Supplier::findOne($v['supplier_id']); echo $supplier->corporation->name; ?></td>
								<td class="projecturl"><? $statusTitle = $status::findOne($v['project_status']); echo !empty($statusTitle->status_title) ? $statusTitle->status_title: 'No Status';  ?></td>
																
							    <td>
								  <?/*=Html::a(Html::tag('span',
									Html::tag('i', '', ['class' => 'fa fa-eye fa-fw','title' => 'view project'])
								 ),['project/view','id' => $v['project_id']]);//= Html::a('test', ['view','id' => $v['tyc_ref']],['div'] ) */?>
								  
									<? 
									  $deletUrl = Url::to(['project/delete','id'=>$v['project_id']]);
									  $updateUrl = Url::to(['project/update','id'=> $v['project_id']]);
											?>
											<p>
												<?= Html::tag('i', '', ['class' => 'fa fa-pencil update', 'data-url'=>$updateUrl]); ?>
												<?= Html::tag('i', '', ['class' => 'fa fa-trash delete', 'data-url'=>$deletUrl]); ?>
											</p>
								</td>
								

							</tr>
							
							<?php $sn++; }?>
			  
						</tbody>
						<tfoot>
							<tr>
								<th>SN</th>
								<th>Folder</th>
								<th>Description</th>
								<th>Client</th>
								<th>Supplier</th>
								<th>Status</th>
								<th>Action</th>
							</tr>
                		</tfoot>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
<? 
		Modal::begin([
			'header' =>'<h1 id="headers"></h1>',
			'id' => 'projectviewcreate',
			'size' => 'modal-md',  
		]);
		echo "<div id='projectcreateform'> </div>";
		Modal::end();
	?>

<script>
$("#projectlistview").DataTable({
        "aaSorting": [],
		"responsive": "true",
		"pagingType": "simple",
    });
</script>