models/Person.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "{{%person}}".
 *
 * @property integer $id
 * @property string $first_name
 * @property string $surname
 * @property string $dob
 * @property string $create_date
 *
 * @property TmPersonCorporation[] $tmPersonCorporations
 */
class Person extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%person}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
		
            [['first_name', 'surname'], 'required'],
			[['dob','person_id'], 'safe'],
            [['first_name', 'surname'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'first_name' => 'First Name',
            'surname' => 'Surname',
            'dob' => 'Dob',
            'create_date' => 'Create Date',
        ];
    }
	
	public function validateDates()
	{
		if(strtotime($this->end_date) <= strtotime($this->start_date)){
			$this->addError('dob','Please give correct Start and End dates');
			$this->addError('end_date','Please give correct Start and End dates');
		}
	}

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPersonCorporations()
    {
        return $this->hasMany(PersonCorporation::className(), ['person_id' => 'id']);
    }
    
     public function getall_person()
	 {
        return $this->hasMany(PersonCorporation::className(), ['person_id' => 'id']);
	 }
    
    public function allrecords()
	{
        return Person::find()->asArray()->all();
    }
	
	public function getPersonEntityId($personId)
	{
		$entityId = Person::findOne(['id' => $personId,]);
		return $entityId->entity_id;
	}
	
	public function getPersonstring() 
	{
		return $this->surname .' '. $this->first_name;
	}
	
	public function getEmailEntities()
	{
		return $this->hasMany(EmailEntity::className(), ['entity_id' => 'entity_id']);
	}
	public function getTelephoneEntities()
	{
		return $this->hasOne(TelephoneEntity::className(), ['entity_id' => 'entity_id']);
	}
	
	public function getEmails()
	{
		return $this->hasMany(Email::className(), ['id' => 'email_id'])->via('emailEntities');
	}
	public function getEmail()
	{
		return $this->hasOne(Email::className(), ['id' => 'email_id'])->via('emailEntities');
	}
	public function getUserEmail()
	{
		return $this->email->address;
	}
	
	public function getTelephone()
	{
		return $this->hasOne(Telephone::className(), ['id' => 'telephone_id'])->via('telephoneEntities');
	}
	public function getUserTelephone()
	{
		return $this->telephone->telephone_number;
	}
}

controllers/PersonController.php
<?php

namespace app\controllers;

use Yii;
use yii\base\Model;
use app\models\Person;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
// test to see if it would work 
use yii\widgets\ActiveForm;

use app\models\Corporation;
use app\models\Email;
use app\models\EmailEntity;
use app\models\Address;
use app\models\Telephone;
use app\models\Entity;
use app\models\Addressentity ;
use app\models\Telephoneentity ;

/**
 * TmpersonController implements the CRUD actions for Tmperson model.
 */
class PersonController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Tmperson models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Person::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Tmperson model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Tmperson model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $person = new Person();
        $email = new Email();
        $address = new Address();
        $telephone = new Telephone();
        $entity = new Entity();
        //calling models for entities
        $email_entity = new EmailEntity ;
        $address_entity = new AddressEntity ;
        $telephone_entity = new TelephoneEntity ;      
       
        if ($telephone->load(Yii::$app->request->post()) & $address->load(Yii::$app->request->post()) &  $person->load(Yii::$app->request->post()) & $email->load(Yii::$app->request->post()) ) {
            
            if( $telephone->validate() & $address->validate() & $person->validate() & $email->validate() ) {
                   $this->createnewperson($entity,$person,$email,$address,$telephone,$email_entity,$address_entity,$telephone_entity);
                   echo 'sent';
            } else {
                echo 'An error occured';
            }    
        }else{
            echo 'not available';
        }
        
    }
    
    public static function createnewperson($entity,$person,$email,$address,$telephone,$email_entity,$address_entity,$telephone_entity)
	{
		$entity->entity_type='person';
        if($entity->save(false)){
			$entity_id = $entity->id;
			$person->entity_id = $entity_id;
			$telephone->save(false);
			$address->save(false) ;
			$person->save(false) ;
			//person id
			$personid = $person->id;
			$email->save(false) ;
		   //fetch all ids
			$telephone_id = $telephone->id;
			$email_id = $email->id;
			$address_id = $address->id;
			//give values to entities
			$email_entity->email_id = $email_id;
			$email_entity->entity_id = $entity_id;
			$address_entity->address_id = $address_id;
			$address_entity->entity_id = $entity_id;
			$telephone_entity->telephone_id = $telephone_id;
			$telephone_entity->entity_id = $entity_id;
			$email_entity->save(false) ;
			$address_entity->save(false) ;
			$telephone_entity->save(false) ;
		}   
    }

    /**
     * Updates an existing Tmperson model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
		$model = $this->findModel($id);
		$emailEntityId = EmailEntity::find()->where(['entity_id'=>$model->entity_id])->one();
		$telephoneEntityId = Telephoneentity::find()->where(['entity_id'=>$model->entity_id])->one();
		$addressEntityId = Addressentity::find()->where(['entity_id'=>$model->entity_id])->one();
        $emailModel = Email::findOne($emailEntityId->email_id);
        $addressModel = Address::findOne($addressEntityId->address_id);
        $telephoneModel =  Telephone::findOne($telephoneEntityId->telephone_id);
		//$model->scenario = 'update';
		//$emailModel->scenario = 'update';
		//$telephoneModel->scenario = 'update';
		//$addressModel->scenario = 'update';
        if ($model->load(Yii::$app->request->post()) && $emailModel->load(Yii::$app->request->post()) && $telephoneModel->load(Yii::$app->request->post()) && $addressModel->load(Yii::$app->request->post()) && $model->validate() && $emailModel->validate() && $telephoneModel->validate() && $addressModel->validate()) {
			$model->save(false);
			$emailModel->save(false);
			$telephoneModel->save(false);
			$addressModel->save(false);
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->renderAjax('update', [
                'personModel' => $model,
				'emailModel' => $emailModel,
				'addressModel' => $addressModel,
				'telephoneModel' => $telephoneModel,
				'id' => $id,
            ]);
        }
    }

    /**
     * Deletes an existing Tmperson model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
        //return $this->redirect(['index']);
    }

    /**
     * Finds the Tmperson model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Tmperson the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Person::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/person/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\Pjax;
use yii\helpers\ArrayHelper;
use kartik\date\DatePicker;


/* @var $this yii\web\View */
/* @var $model app\models\Tmuser */
/* @var $personsform yii\widgets\ActiveForm */
?>
<?php Pjax::begin(['id' => 'personformpjax']) ?>
<div class="user-form">
	<?php $personsform = ActiveForm::begin(['action' =>[$action],'enableClientValidation' => true, 'attributes' => $personModel->attributes(),'enableAjaxValidation' => false,'id' => 'personforms']); ?>

    
     <?//=$personsform->field($model, 'person_id')->dropdownList(ArrayHelper::map($person1, 'id',function($test){return $test['first_name'].' '.$test['surname']; }));?>

	<div  class="indexFormContainer">
		<section class="indexFormTitle"> Basic info </section>
		<?= $personsform->field($personModel, 'first_name')->textInput() ?>

		<?= $personsform->field($personModel, 'surname')->textInput(['maxlength' => true]) ?>

		
		<?= $personsform->field($personModel, 'dob')->widget(DatePicker::classname(), [
							'options' => ['placeholder' => 'Select issue date ...'],
							 'pluginOptions' => [
								 'format' => 'yyyy-mm-dd',
								 'todayHighlight' => true
									]
								]) 
		?>
	</div>

	<div class="indexFormContainer">
		<section class="indexFormTitle"> Contact details </section>
		<?= $personsform->field($telephoneModel, 'telephone_number')->textInput(['maxlength' => true]) ?>

		<?= $personsform->field($emailModel, 'address')->textInput(['maxlength' => true]) ?>
		<?= $personsform->field($addressModel, 'address_line')->textInput(['maxlength' => true]) ?>

		<?= $personsform->field($addressModel, 'state')->textInput(['maxlength' => true]) ?>

		<?= $personsform->field($addressModel, 'country')->textInput(['maxlength' => true]) ?>

		<?= $personsform->field($addressModel, 'code')->textInput(['maxlength' => true]) ?>
	</div>

    <div class="form-group">
		<p>
			<br>
        	<?= Html::submitButton($personModel->isNewRecord ? '<span id="perbuttonText">Create</span> <img id="perloader" src="images/45.gif" " /> <span id="perloader1"><span>' : 'Update', ['class' => $personModel->isNewRecord ? 'btn btn-danger' : 'btn btn-danger','id'=>'persubmit_id']) ?>
		</p>

    </div>

    <?php ActiveForm::end(); ?>

</div>
<?php Pjax::end(); ?>

<?php 
if($personModel->isNewRecord){
	$personJs = <<<JS

$('#personforms').on('beforeSubmit', function (e) {
	$('#perbuttonText').hide();
 	$('#perloader').show();
    var \$personsform = $(this);
    $.post(\$personsform.attr('action'),\$personsform.serialize())
    .always(function(result){
	
	$(document).find('#perloader').hide();
   if(result=='sent'){
	   
	   $(document).find('#perloader1').html(result).show();
	   $(document).find('#flash').append(result).show();
	   
	 
	   $(document).find('#personforms').trigger('reset');
	   $("html, body").delay(200).animate({
        scrollTop: $('#flash').offset().top
		
    }, 2000);
		
	   $('#dashboard').modal('toggle');
	 	$.pjax.reload({container:"#person_reload",async: false
}); 
	  
	   
    
    }else{
    $(document).find('#perloader1').html(result).show();
	
    }
    }).fail(function(){
    console.log('Server Error');
    });
	
	setTimeout(function(){ 
	$(document).find('#perloader').hide();
	$(document).find('#perloader1').hide();
	$(document).find('#perbuttonText').show();
	}, 5000);
    return false;
    
    
    
});
JS;

} else {
	
	$personJs = <<<JS

$('#personforms').on('beforeSubmit', function (e) {
	$('#perbuttonText').hide();
 	$('#perloader').show();
    var \$personsform = $(this);
    $.post(\$personsform.attr('action')+'&id='+$id,\$personsform.serialize())
    .always(function(result){
	
	$(document).find('#perloader').hide();
   if(result=='sent'){
	   
	   $(document).find('#perloader1').html(result).show();
	   $(document).find('#flash').append(result).show();
	   
	 
	   $(document).find('#personforms').trigger('reset');
	   $("html, body").delay(200).animate({
        scrollTop: $('#flash').offset().top
		
    }, 2000);
		
	   $('#dashboard').modal('toggle');
	 	$.pjax.reload({container:"#person_reload",async: false
}); 
	  
	   
    
    }else{
    $(document).find('#perloader1').html(result).show();
	
    }
    }).fail(function(){
    console.log('Server Error');
    });
	
	setTimeout(function(){ 
	$(document).find('#perloader').hide();
	$(document).find('#perloader1').hide();
	$(document).find('#perbuttonText').show();
	}, 5000);
    return false;
    
    
    
});
JS;

}
 
$this->registerJs($personJs);
?>

views/person/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Tmperson */

$this->title = 'Create Person';
$this->params['breadcrumbs'][] = ['label' => 'People', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="person-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/person/dashboardpersonlist.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;

?>

<div class="folder-index">

										
										
										<div class="box-body">

											<table id="person_table" class="table table-bordered table-striped">
												
												<thead>
													<tr>
														<th>Surname</th>
														<th>First Name</th>
														<th>Action</th>
													</tr>
												</thead>
												<tbody>
													
												<?php foreach($displayAllPerson as $key => $persons){  ?>
												
													<tr>
													
													<td>
														<?=$persons->surname; ?>
													</td>
														<td>
															<?=$persons->first_name; ?>
															
														</td>
														<td>
															<? $deletUrl=Url::to(['person/delete','id'=>$persons->id]);
															$updateUrl=Url::to(['person/update','id'=>$persons->id]);
															?>
															<p>
        <?= Html::tag('i', '', ['class' => 'fa fa-pencil update', 'data-url'=>$updateUrl]); ?>
        <?= Html::tag('i', '', ['class' => 'fa fa-trash delete', 'data-url'=>$deletUrl]); ?>
    </p>
														</td>
													</tr>
												
												<? } ?>
												</tbody>
												<tfoot>
													<tr>
														<th></th>
													</tr>
												</tfoot>

											</table>
										</div>
              
									</div>

<?
$string = '<span id="newperson" class="btn btn-black"><span class = "main">Create</span><span class = "hide" style = "display:none">Create Contacts</span></span>';
$javascriptPersonButton =  "$('#person_table_length').html('".$string."')";
$loaderImage ='<img class="loadergif" src="images/loader.gif"  />';
$this->registerJs(
    "$('document').ready(function(){ 
	
	$('#person_table').DataTable({
        'aaSorting': [],
		'pagingType': 'simple',
		
    });
	
	
	
	
	
	
	".$javascriptPersonButton."
	
	});"
	
	
);
?>

views/person/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Person';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="person-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create person', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'first_name',
            'surname',
            'dob',
            'entity_id',
            // 'create_date',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

views/person/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Tmperson */


?>
<div class="person-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
								'action' => 'person/update',
								'id' => $id,
							   'personModel' => $personModel,
							   'emailModel' => $emailModel,
							   'telephoneModel' => $telephoneModel,
							   'addressModel' => $addressModel,]) ?>

</div>

views/person/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Tmperson */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'people', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="person-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'first_name',
            'surname',
            'dob',
            'entity_id',
            'create_date',
        ],
    ]) ?>

</div>