models/Supplier.php
<?php

namespace app\models;

use Yii;
use app\boffins_vendor\behaviors\DeleteUpdateBehavior;

/**
 * This is the model class for table "{{%supplier}}".
 *
 * @property integer $id
 * @property integer $corporation_id
 * @property string $supplier_type
 * @property string $notes
 *
 * @property Project[] $Projects
 * @property Corporation[] $Corporation

 */
class Supplier extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%supplier}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['corporation_id'], 'required'],
            [['corporation_id'], 'integer'],
            [['supplier_type', 'notes'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
	
	public function behaviors(){
		 return [
		"deleteUpdateBehavior2" => DeleteUpdateBehavior::className(),
			 ];
	}
	
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'corporation_id' => 'Corporation ID',
            'supplier_type' => 'Supplier Type',
            'notes' => 'Notes',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProjects()
    {
        return $this->hasMany(Project::className(), ['supplier_id' => 'id']);
    }
    
    /**
     * CHANGES BY BOFFINS
     */
	 
	//Added by Kingsley 
    public static function get_all_supplierid()
	{
        $suppliers = Supplier::find()->asArray()->indexBy('id')->all();        
        return $suppliers;
    }
	
	//Added by Anthony
	
	public function getCorporation() 
	{
		return $this->hasOne(Corporation::className(), ['id' => 'corporation_id'] );
	}
	
	public function getName() 
	{
		return $this->corporation->name;
	}
	
	public function getShortName() 
	{
		return $this->corporation->shortName;
	}
	
	public function getNameString() 
	{
		return $this->corporation->NameString;
	}
	
	
}

controllers/SupplierController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Supplier;
use app\models\Corporation;
use app\models\Person;
use app\models\Email;
use app\models\Address;
use app\models\Telephone;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * SupplierController implements the CRUD actions for Supplier model.
 */
class SupplierController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Supplier models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Supplier::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Supplier model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Supplier model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Supplier();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
			echo 'sent';
            
        } else {
			echo 0;
            
        }
    }

    /**
     * Updates an existing Supplier model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Supplier model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Supplier model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Supplier the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Supplier::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
	
	public function actionAdhocsupplier()
    {
        
		
		$corporationModel = new Corporation();
        
		//$client = new Client;
		$supplier = new Supplier;
		$personModel = new Person();
		$email = new Email();
		$address = new Address();
		$telephone = new Telephone();
        
		
        //Calling requied model methods 
		//$getNewClien = $corporationModel->fetchNewClient();
		$getNewSupplier = $corporationModel->fetchNewSupplier();
		

        return $this->renderAjax('adhocsupplier',[
			//'newClient' => $getNewClien,
			//'clientModel'=>$client,
			'newSupplier' => $getNewSupplier,
			'supplierModel'=>$supplier,
			'corporationModel' => $corporationModel,
			'personModel' => $personModel,
            'emailModel' => $email,
            'addressModel' => $address,
            'telephoneModel' => $telephone,
		
			

        ]);
    }
	
	public function actionNewsupplier()
    {
       	$model = new Supplier();
		$data = [];
		$findLastAdedClient = $model->find()->orderBy(['id' => SORT_DESC])->one();
		Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
		$data['clientId'] = $findLastAdedClient->id;
		$data['corpName'] = $findLastAdedClient->name ;
        return $data;
    }

}

views/supplier/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Supplier */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="supplier-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'corporation_id')->textInput() ?>

    <?= $form->field($model, 'supplier_type')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'notes')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/supplier/adhocsupplier.php
<div id='suppliercontent' class='hideall'>
	<div class="nav-tabs-custom">
		<ul class="nav nav-tabs pull-right">
			<li class="active"><a href="#useexistingsup" data-toggle="tab">Use Existing</a></li>
			<li><a href="#usenewsup" data-toggle="tab">Create new supplier</a></li>
		  
		  
		</ul>
		<div class="tab-content">
			<!-- /.tab-pane -->
			<div class="tab-pane active" id="useexistingsup">
				<div class="box">
					<h1 style="text-align:center;">Use Existing </h1>
					<div class="folder-index">
						<h1></h1>
						<div class="box-body">
						   <?= $this->render('/site/supplier_form',
												  ['newSupplier' =>$newSupplier,
												   'supplierModel'=>$supplierModel,
												   ]) 
								?>
						</div>
					</div>
				</div>
			</div>
			<!-- /.tab-pane -->
			<div class="tab-pane" id="usenewsup">
				<div class="box">
					<h1 style="text-align:center;"></h1>
					<div class="folder-index">
						<div class="box-body">
							<h1>Create new supplier</h1>
							<?= $this->render('../supplier/dashboardcreatesupplier',[
							  'corporation1' => $corporationModel,
							  //'action' => $action,
							  'personModel' => $personModel,
							  'emailModel' => $emailModel,
							  'telephoneModel' => $telephoneModel,
							  'addressModel' => $addressModel,
							  'hiddenValue' => 'supplier',
							  'actionid'=>'supplier',]) 
								?>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- /.tab-content -->
	</div>
</div>

views/supplier/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Supplier */

$this->title = 'Create Supplier';
$this->params['breadcrumbs'][] = ['label' => 'Suppliers', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="supplier-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
		
    ]) ?>

</div>

views/supplier/dashboardcreatesupplier.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

use yii\widgets\Pjax;
use yii\helpers\ArrayHelper;


/* @var $this yii\web\View */
/* @var $model app\models\Tmuser */
/* @var $form yii\widgets\ActiveForm */
?>
<style>
	#suppliloader,#suppliloader1{
		display: none;
	}
	
</style>
<?php Pjax::begin(['id' => 'supplierformpjax']) ?>
<div class="corporation-form">
	<?  $formId = $hiddenValue; ?>
	<?php $form = ActiveForm::begin(['action' =>['corporation/create'],'enableClientValidation' => true, 'attributes' => $corporation1->attributes(),'enableAjaxValidation' => false,'id' => 'dashboardsupplier']); ?>
	

     <?//=$form->field($model, 'person_id')->dropdownList(ArrayHelper::map($person1, 'id',function($test){return $test['first_name'].' '.$test['surname']; }));?>

	<div  class="indexFormContainer">
		<section class="indexFormTitle"> Basic info </section>
    <?= $form->field($corporation1, 'name')->textInput() ?>

    <?= $form->field($corporation1, 'short_name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($corporation1, 'notes')->textInput(['maxlength' => true]) ?>
    </div>

 	<div class="indexFormContainer">
		<section class="indexFormTitle"> Contact details </section>

    <?= $form->field($telephoneModel, 'telephone_number')->textInput(['maxlength' => true]) ?>

    <?= $form->field($emailModel, 'address')->textInput(['maxlength' => true]) ?>
    <?= $form->field($addressModel, 'address_line')->textInput(['maxlength' => true]) ?>

    <?= $form->field($addressModel, 'state')->textInput(['maxlength' => true]) ?>

    <?= $form->field($addressModel, 'country')->textInput(['maxlength' => true]) ?>

    <?= $form->field($addressModel, 'code')->textInput(['maxlength' => true]) ?>
    
	</div>
    
	
	
	<div class="form-group">
		<p>
			<br>
			<?= Html::hiddenInput('corporationhidden[hidden]', $hiddenValue) ?>
        	<?= Html::submitButton($corporation1->isNewRecord ? '<span id="supplibuttonText">Create</span> <img id="suppliloader" src="images/45.gif"  /> <span id="suppliloader1"><span>' : 'Update', ['class' => $corporation1->isNewRecord ? 'btn btn-danger' : 'btn btn-danger','id'=>'supsupplier_id']) ?>
		</p>
    </div>

    <?php ActiveForm::end(); ?>

</div>
<?php Pjax::end() ?>

<?php 
$getSupplier = Url::to(['/supplier/newsupplier']);
$supplierDashboardFrom = <<<JS

$('#dashboardsupplier').on('beforeSubmit', function (e) {
	$('#supplibuttonText').hide();
 	$('#suppliloader').show();
    var \$form = $(this);
    $.post(\$form.attr('action'),\$form.serialize())
    .always(function(result){
	
	$(document).find('#suppliloader').hide();
   if(result=='sent'){
   
   
   
   
   if($(document).find('#clientsupplier').length){
	  
	  	$.get("$getSupplier", function(data){
        	$(document).find('.supplierRefesh select').prepend('<option selected value="'+data.clientId+'" >'+data.corpName+'</option>');
    	});
	  
	  	
	  	$(document).find('#clientsupplier').modal('toggle');
		
	  
	  } else{
	  
	  		   $(document).find('#suppliloader1').html(result).show();
	    $(document).find('#flash').append(result).show();
	   
	 
	   $(document).find('#dashboardsupplier').trigger('reset');
	   $("html, body").delay(200).animate({
        scrollTop: $('#flash').offset().top
		
    }, 2000);
		
	   $('#dashboard').modal('toggle');
	 	$.pjax.reload({container:"#supplier_reload",async: false
});
	  }
	   
	    
	  
    }else{
    $(document).find('#suppliloader1').html(result).show();
	
    }
    }).fail(function(){
    console.log('Server Error');
    });
	
	setTimeout(function(){ 
		$(document).find('#suppliloader').hide();
		$(document).find('#suppliloader1').hide();
		$(document).find('#supplibuttonText').show();
	}, 5000);
    return false;
    
    
    
});
JS;
 
$this->registerJs($supplierDashboardFrom);
?>

views/supplier/dashboardsupplierlist.php
<?
use yii\helpers\Html;
use yii\helpers\Url;
?>
<div class="folder-index">

										
										
										<div class="box-body">

											<table id="supplier_table" class="table table-bordered table-striped">
												
												<thead>
													<tr>
														<th>Name</th>
														<th>Short Name</th>
														<th>Action</th>
													</tr>
												</thead>
												<tbody>
												<?php foreach($displayAllSupplier as $key => $supplier){ $corporation=$corporationModel->findOne($supplier['corporation_id']); ?>
												
													<tr>
													
													<td>
														<?=$corporation->name; ?>
									
													</td>
													<td>
														<?=$corporation->short_name; ?>
									
													</td>
													<td>
														<? $deletUrl=Url::to(['supplier/delete','id'=>$supplier->id]);
														$updateUrl=Url::to(['corporation/update','id'=> $corporation->id]);
														?>
														<p>
															<?= Html::tag('i', '', ['class' => 'fa fa-pencil update', 'data-url'=>$updateUrl]); ?>
															<?= Html::tag('i', '', ['class' => 'fa fa-trash delete', 'data-url'=>$deletUrl]); ?>
														</p>
									
													</td>
													</tr>
												
												<? } ?>
												</tbody>
												<tfoot>
													<tr>
														<th></th>
													</tr>
												</tfoot>

											</table>
										</div>
              
									</div>

<?
$string = '<span id="newsupplier" class="btn btn-black"><span class = "main">Create</span><span class = "hide" style = "display:none">Create suppliers</span></span>';
$javascriptSupplierButton =  "$('#supplier_table_length').html('".$string."')";
$this->registerJs(
    "$('document').ready(function(){ 
	
	$('#supplier_table').DataTable({
        'aaSorting': [],
		'pagingType': 'simple',
		
    });
	
	".$javascriptSupplierButton."
	
	});"
	
	
);
?>

views/supplier/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Suppliers';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="supplier-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Supplier', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'corporation_id',
            'supplier_type',
            'notes',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

views/supplier/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Supplier */

$this->title = 'Update Supplier: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Suppliers', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="supplier-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/supplier/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Supplier */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Suppliers', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="supplier-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'corporation_id',
            'supplier_type',
            'notes',
        ],
    ]) ?>

</div>